name: CI - build, tests, lint

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build_job:
    name: Build (Unit-tests & Android-Lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew build
      - name: Archive output artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: output-artifacts
          path: |
            app/build/outputs
            app/build/reports
  android_ui_test_job:
    name: Android UI-tests on emulator
    needs: build_job
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        api-level: [16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run debug UI-tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          script: ./gradlew :app:connectedCheck -PtestBuildType=debug
      - name: Run release UI-tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          script: ./gradlew :app:connectedCheck -PtestBuildType=release
